### ISSUE TITLE
Failling to Test DevKit Installation

### ISSUE THREAD

**Issue by brnrc** [oneclick/rubyinstaller#164]
Hi guys, I'm trying to set my dev environment on my PC, so I went through the installation process and got stuck:
(I did the previous steps, pasting the last two only)
First I did this:

```
C:\Ruby200-x64\DevKit>ruby dk.rb install
[INFO] Skipping existing gem override for 'C:/Ruby200-x64'
[WARN] Skipping existing DevKit helper library for 'C:/Ruby200-x64'
```

And then this:

```
C:\Ruby200-x64\DevKit>gem install bson_ext --platform=ruby -p
Fetching: bson-1.8.4.gem (100%)
Successfully installed bson-1.8.4
Fetching: bson_ext-1.8.4.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing bson_ext:
        ERROR: Failed to build gem native extension.

C:/Ruby200-x64/bin/ruby.exe extconf.rb
checking for asprintf()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=C:/Ruby200-x64/bin/ruby
C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:431:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:516:in `try_link0'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:531:in `try_link'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:717:in `try_func'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:1001:in `block in have_func'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:892:in `block in checking_for'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:337:in `block (2 levels) in postpone'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:307:in `open'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:337:in `block in postpone'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:307:in `open'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:333:in `postpone'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:891:in `checking_for'
    from C:/Ruby200-x64/lib/ruby/2.0.0/mkmf.rb:1000:in `have_func'
    from extconf.rb:3:in `<main>'
```

I also tried Scenario A and B of the troubleshooting guide, both without success.
Moving out to Linux until then...
Thank you.

**Comment by codelearner777** [comment]
hi guys,
I am following this guide to install ruby dev kit.
https://github.com/oneclick/rubyinstaller/wiki/Development-Kit
and I failed in step5.
![image](https://cloud.githubusercontent.com/assets/14092572/10762067/f0344d4c-7cf6-11e5-8a6e-c2d5d9a16872.png)

I use rubyinstaller-2.2.3-x64.exe and DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe.

could someone help me, please?

**Comment by seanvree** [comment]
Hate to open this issue again, but I'm having the same issue. is there a fix?

```
C:\Users\Administrator>cd C:\Ruby24-x64

C:\Ruby24-x64>which ruby
/cygdrive/c/Ruby24-x64/bin/ruby

C:\Ruby24-x64>gem install json --platform=ruby
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170602-32744-jv5yes.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-2.1.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-2.1.0/gem_make.out

C:\Ruby24-x64>

```

**Comment by larskanis** [comment]
@seanvree You need to install the development tools first per `ridk install`.  See also https://stackoverflow.com/a/44244005/4743028

**Comment by seanvree** [comment]
@larskanis  - 


Right, I actually saw that after I posted, this 

So if we have ruby 2.4 then we don't need the Devkit if we have MSYS2 ?

**Comment by DiogoMiranda** [comment]
Thanks, help me.

**Comment by KasunPrabath** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
