### ISSUE TITLE
rake aborted! wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by kbhat** [oneclick/rubyinstaller#370]
I am getting this error while trying to build latest rubyinstaller from source on Windows machine.
Steps followed:
1. Clone git://github.com/oneclick/rubyinstaller.git under C:\users\bhattk\repo\rubyinstaller
2. Ensure the requirements are met:
    2a) "ruby --version" returned ruby '1.8.6 (2007-09-24 patchlevel 111) [i386-mswin32]'
    2b) "rake --version" returned 'rake, version 0.7.3'
    2c) Ensured zlib1.dll is present in ruby's bin directory
3. Run "rake ruby22". I get an error message at this stage:
<i>C:\Users\bhattk\repo\rubyinstaller>rake
(in C:/Users/bhattk/repo/rubyinstaller)
rake aborted!
wrong number of arguments (2 for 1)
C:/Users/bhattk/repo/rubyinstaller/rakefile.rb:46:in `load'
(See full trace by running task with --trace)</i>
------------
With trace option enabled:
C:\Users\bhattk\repo\rubyinstaller>rake ruby22 --trace
(in C:/Users/bhattk/repo/rubyinstaller)
Loading mingw.rb
Loading mingw64.rb
Loading mingwbuilds.rb
Loading tdm_mingw.rb
Loading certificate.rake
Loading common.rake
Loading defaults.rake
Loading knapsack.rake
Loading openssl.rake
Loading rbreadline.rake
Loading tk.rake
Loading devkit.rake
rake aborted!
wrong number of arguments (2 for 1)
C:/Users/bhattk/repo/rubyinstaller/recipes/devkit/devkit.rake:41:in `task'
C:/Users/bhattk/repo/rubyinstaller/recipes/devkit/devkit.rake:41
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1571:in `in_namespace'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:641:in `namespace'
C:/Users/bhattk/repo/rubyinstaller/recipes/devkit/devkit.rake:35
C:/Users/bhattk/repo/rubyinstaller/rakefile.rb:46:in `load'
C:/Users/bhattk/repo/rubyinstaller/rakefile.rb:46
C:/Users/bhattk/repo/rubyinstaller/rakefile.rb:44:in `each'
C:/Users/bhattk/repo/rubyinstaller/rakefile.rb:44
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1940:in `load'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1940:in `raw_load_rakefile'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1727:in `load_rakefile'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1761:in `standard_exception_handling'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1726:in `load_rakefile'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1710:in `run'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1761:in `standard_exception_handling'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/lib/rake.rb:1708:in `run'
T:/win32/ruby-1.8.6/lib/ruby/gems/1.8/gems/rake-0.7.3/bin/rake:7
T:/win32/ruby-1.8.6/bin/rake:16:in `load'
T:/win32/ruby-1.8.6/bin/rake:16

**Comment by kbhat** [comment]
Kindly make the change in "Requirements" section of README.md.
